version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  app:
    build:
      context: .
      args:
        NODE_ENV: production

    ports:
      - "3000:3000"

    depends_on:
      - db

    env_file:
      - .env.production

    restart: always

  db:
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env.production
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

