name: Deploy Backend

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Connect to VPS and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          script: |
            echo "📦 Start deploy on server..."
            bash /app/scripts/deploy.sh

            echo "🔍 healthcheck..."
            for i in {1..10}; do
              STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000/healthcheck)
              if [ "$STATUS" -eq 200 ]; then
                echo "✅ App ready!!"
                break
              else
                echo "⏳ Waiting readiness (попытка $i)..."
                sleep 2
              fi
            done
